services:
  api:
    build:
      context: ./backend/MCPApi
      dockerfile: Dockerfile
    ports:
      - "8282:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/app.db
