services:
  api:
    build:
      context: ./backend/MCPApi
      dockerfile: Dockerfile
    ports:
      - "8282:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/app.db

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    # environment:
    #   - N8N_HOST=n8n.sardonnay.co.za
    #   - N8N_PORT=5678
    #   - N8N_PROTOCOL=https
    #   - N8N_BASIC_AUTH_ACTIVE=true
    #   - N8N_BASIC_AUTH_USER=admin
    #   - N8N_BASIC_AUTH_PASSWORD=admin_password
    #   - GENERIC_TIMEZONE=Johannesburg
    volumes:
      - ./n8n/data:/home/node/.n8n
